 const courseslist=[{
  "courseMasterList": {
    "PH201": { "title": "Introduction to Electrodynamics", "credits": 4 },
    "PH202": { "title": "Introduction to Quantum Physics", "credits": 4 },
    "PH203": { "title": "Solid State Physics", "credits": 4 },
    "PH404": { "title": "Molecular and Crystal Physics", "credits": 4 },
    "PH503": { "title": "Quantum Mechanics I", "credits": 4 },
    "PH505": { "title": "Classical Electrodynamics", "credits": 4 },
    "PH507": { "title": "Statistical Mechanics", "credits": 4 },
    "PH508": { "title": "Classical Mechanics", "credits": 4 },
    "PH509": { "title": "Computational Physics", "credits": 4 },
    "PH510": { "title": "Condensed Matter Physics", "credits": 4 },
    "CH203": { "title": "Fundamentals and Applications of Spectroscopy", "credits": 4 },
    "CH204": { "title": "Organic Chemistry in Everyday Life", "credits": 4 },
    "CH302": { "title": "Electrochemical Science and Engineering", "credits": 4 },
    "CH401": { "title": "Food Chemistry", "credits": 4 },
    "CH511": { "title": "Quantum Chemistry", "credits": 4 },
    "CG503": { "title": "Fundamentals of Cognitive Psychology", "credits": 4 },
    "CG505": { "title": "Fundamental Neuroscience", "credits": 4 },
    "EH303": { "title": "Introduction to Earth Sciences", "credits": 4 },
    "EH304": { "title": "Drone Data Acquisition Processing and Interpretation", "credits": 4 },
    "EH601": { "title": "Earth Surface Processes", "credits": 4 },
    "EH602": { "title": "River Morphology and Ecology", "credits": 4 },
    "EH605": { "title": "Modeling of Earth System and Sustainability", "credits": 4 },
    "EH608": { "title": "Biodiversity Conservation and Sustainable Development", "credits": 4 },
    "EH611": { "title": "Near Surface Geophysics", "credits": 4 },
    "EH612": { "title": "Ocean and Global Change", "credits": 4 },
    "EH619": { "title": "Geobiology", "credits": 4 },
    "EH621": { "title": "Climate of the Past", "credits": 4 },
    "MA204": { "title": "Introduction to Partial Differential Equations", "credits": 2 },
    "MA205": { "title": "Calculus of Several Variables", "credits": 2 },
    "MA206": { "title": "Introduction to Complex Analysis", "credits": 2 },
    "CS333": { "title": "Ethics of AI", "credits": 4 },
    "CS613": { "title": "Natural Language Processing", "credits": 4 },
    "ES615": { "title": "Nature Inspired Computing", "credits": 4 },
    "ES645": { "title": "Optimization Methods in Machine Learning", "credits": 4 },
    "ES659": { "title": "Computer Graphics", "credits": 4 },
    "ES661": { "title": "Probabilistic Machine Learning", "credits": 4 },
    "ES666": { "title": "Computer Vision", "credits": 4 },
    "ES667": { "title": "Deep Learning", "credits": 4 },
    "ES670": { "title": "Matrix Methods for Signal Processing, Data Science, and Machine Learning", "credits": 4 },
    "ES676": { "title": "Classical Information Theory", "credits": 4 },
    "ME639": { "title": "Introduction to Robotics", "credits": 4 },
    "CS301": { "title": "Operating Systems", "credits": 4 },
    "CS327": { "title": "Compilers", "credits": 4 },
    "CS432": { "title": "Databases", "credits": 4 },
    "CS433": { "title": "Computer Networks", "credits": 4 },
    "CS436": { "title": "History of Computing and its Applications to Domains", "credits": 4 },
    "EE323": { "title": "Digital Signal Processing", "credits": 4 },
    "ES214": { "title": "Discrete Mathematics", "credits": 4 },
    "ES669": { "title": "Advanced Computer Architecture and Systems", "credits": 4 },
    "BS401": { "title": "Nanoscale Science", "credits": 4 },
    "CL324": { "title": "Introduction to Polymer Science and Engineering", "credits": 4 },
    "CL353": { "title": "Introduction to Process Safety", "credits": 4 },
    "CL426": { "title": "Biochemical Engineering", "credits": 4 },
    "CL427": { "title": "Formulation Science and Engineering", "credits": 4 },
    "ES604": { "title": "Engineering Optimization", "credits": 4 },
    "ES617": { "title": "Design of Experiments", "credits": 4 },
    "ES658": { "title": "Molecular Simulations - Theory and Applications", "credits": 4 },
    "ES662": { "title": "Flexible Electronics: Materials, Methods and Devices", "credits": 4 },
    "ES664": { "title": "Scientific Computing using C++", "credits": 4 },
    "CL601": { "title": "Advance Transport Phenomena", "credits": 4 },
    "CL602": { "title": "Advanced Thermodynamics", "credits": 4 },
    "CL604": { "title": "Advanced Reaction Engineering", "credits": 4 },
    "CL605": { "title": "Colloidal Domain: Where Science Meets Engineering", "credits": 4 },
    "CL627": { "title": "Particulate Solids: Processing & Surface Engineering", "credits": 4 },
    "CL628": { "title": "Liquid State Theory", "credits": 4 },
    "CL629": { "title": "Fundamentals of Aerosol Science", "credits": 4 },
    "CL630": { "title": "Catalyst Design for Heterogeneous Reactions", "credits": 4 },
    "CE634": { "title": "Air Pollution Control Engineering", "credits": 4 },
    "CE313": { "title": "Environmental Science and Engineering", "credits": 4 },
    "CE314": { "title": "Geotechnical Engineering", "credits": 4 },
    "CE404": { "title": "Transportation Engineering", "credits": 4 },
    "CE307": { "title": "Masonry Design", "credits": 2 },
    "CE603": { "title": "Constitutive Models in Soil Mechanics", "credits": 4 },
    "CE605": { "title": "Remote Sensing of Land and Water Resources", "credits": 4 },
    "CE607": { "title": "Advanced Structural Analysis", "credits": 4 },
    "CE611": { "title": "Advanced Engineering Hydrology", "credits": 4 },
    "CE613": { "title": "Analysis and Design of Masonry Buildings", "credits": 4 },
    "CE615": { "title": "Structural Design for Fire", "credits": 4 },
    "CE622": { "title": "Structural Dynamics", "credits": 4 },
    "CE624": { "title": "River Engineering", "credits": 4 },
    "CE625": { "title": "Advanced Hydraulic Engineering", "credits": 4 },
    "CE626": { "title": "Earthquake Engineering", "credits": 4 },
    "CE627": { "title": "Slopes and Retaining Structures", "credits": 4 },
    "CE628": { "title": "Applied Hydraulic Transients", "credits": 4 },
    "CE629": { "title": "Geosynthetics", "credits": 4 },
    "CE631": { "title": "Irrigation Engineering and Hydraulic Structures", "credits": 4 },
    "CE632": { "title": "Advanced Concrete Design", "credits": 4 },
    "CE635": { "title": "Pavement Materials and Design", "credits": 4 },
    "CE636": { "title": "Traffic and Roadway Engineering", "credits": 4 },
    "CE637": { "title": "Infrastructure Systems: Planning and Management", "credits": 4 },
    "CE638": { "title": "Advanced Concrete Technology", "credits": 4 },
    "EH610": { "title": "Engineering Seismology and Seismic Hazard Analysis", "credits": 4 },
    "ES404": { "title": "Networks and Complex Systems", "credits": 4 },
    "ES607": { "title": "Foundations of Fluid Dynamics", "credits": 4 },
    "ES621": { "title": "Advanced Solid Mechanics", "credits": 4 },
    "ES622": { "title": "Finite Element Methods", "credits": 4 },
    "ES624": { "title": "Non-Linear Elasticity", "credits": 4 },
    "ES635": { "title": "Water Quality Engineering", "credits": 4 },
    "ES646": { "title": "Elastodynamics and Vibrations", "credits": 4 },
    "ES648": { "title": "Nonlinear Dynamics and Vibrations", "credits": 4 },
    "ES651": { "title": "Computational Inelasticity", "credits": 4 },
    "ES652": { "title": "Contaminant Transport and Remediation", "credits": 4 },
    "ES653": { "title": "Nonlinear Continuum Mechanics", "credits": 4 },
    "ES660": { "title": "Variational Methods in Mechanics", "credits": 4 },
    "ES671": { "title": "Mechanics of Composite Materials", "credits": 4 },
    "ME605": { "title": "Computational Fluid Dynamics", "credits": 4 },
    "ME628": { "title": "Advanced Fluid Mechanics", "credits": 4 },
    "ME640": { "title": "Fracture Mechanics", "credits": 4 },
    "ES335": { "title": "Machine Learning", "credits": 4 },
    "ES627": { "title": "Linear Algebra and Computation", "credits": 4 },
    "ES637": { "title": "Mathematical Foundations for Computer Vision and Graphics", "credits": 4 },
    "CS614": { "title": "Advanced Algorithms", "credits": 4 },
    "CS617": { "title": "Computational Complexity Theory", "credits": 4 },
    "CS328": { "title": "Introduction to Data Science", "credits": 4 },
    "CS332": { "title": "Principles of Programming Languages", "credits": 4 },
    "CS431": { "title": "Computer and Network Security", "credits": 4 },
    "CS434": { "title": "Software Engineering and Testing", "credits": 4 },
    "CS435": { "title": "Human-Computer Interaction", "credits": 4 },
    "CS615": { "title": "Advanced Networks", "credits": 4 },
    "CS616": { "title": "Parallel and Distributed Systems", "credits": 4 },
    "ES668": { "title": "5G and Beyond", "credits": 4 },
    "ES215": { "title": "Computer Organization and Architecture", "credits": 4 },
    "ES333": { "title": "Microprocessors and Embedded Systems", "credits": 4 },
    "ES412": { "title": "Optical Fiber Communication", "credits": 4 },
    "ES414": { "title": "Introduction to Photonics", "credits": 4 },
    "ES416": { "title": "Space Science and Satellite Technology", "credits": 4 },
    "ES408": { "title": "Mechatronics", "credits": 4 },
    "ES612": { "title": "Artificial Intelligence", "credits": 4 },
    "ES613": { "title": "Modern Control Theory", "credits": 4 },
    "ES616": { "title": "Digital Control Systems", "credits": 4 },
    "ES625": { "title": "Optical Communications", "credits": 4 },
    "ES626": { "title": "Microfabrication and Semiconductor Processes", "credits": 4 },
    "ES641": { "title": "Electronic Instrumentation", "credits": 4 },
    "ES642": { "title": "Control of Nonlinear Dynamical Systems", "credits": 4 },
    "ES655": { "title": "Medical Imaging Systems", "credits": 4 },
    "ES656": { "title": "Human-Robot Interaction", "credits": 4 },
    "ES657": { "title": "Biomedical Ultrasound", "credits": 4 },
    "ES663": { "title": "Smart Renewable Energy Systems", "credits": 4 },
    "ES665": { "title": "Advanced Transportation Electrification Technology", "credits": 4 },
    "ES675": { "title": "Photonics - Principles and Applications", "credits": 4 },
    "PH643": { "title": "Quantum Computing and Information", "credits": 4 },
    "EE651": { "title": "CMOS Analog IC Design", "credits": 4 },
    "EE660": { "title": "Power Management IC Design", "credits": 4 },
    "ES246": { "title": "Vacuum Technology Laboratory", "credits": 2 },
    "ES672": { "title": "Semiconductor Packaging", "credits": 4 },
    "ES631": { "title": "Advanced Heat Transfer", "credits": 4 },
    "ES632": { "title": "Energy Systems", "credits": 4 },
    "MSE313": { "title": "Polymers, Ceramics & Composites", "credits": 4 },
    "MSE632": { "title": "Characterization of Materials", "credits": 4 },
    "FP100": { "title": "Foundation Programme", "credits": 4 },
    "MA101": { "title": "Mathematics I", "credits": 4 },
    "ES101": { "title": "Engineering Graphics", "credits": 3 },
    "ES103": { "title": "Introduction to Electrical Systems", "credits": 4 },
    "BE101": { "title": "Introduction to Life Sciences: Fundamentals of Life", "credits": 4 },
    "PE101": { "title": "Physical Education", "credits": 0 },
    "HS151": { "title": "Economics", "credits": 4 },
    "MA102": { "title": "Mathematics II", "credits": 4 },
    "ES104": { "title": "Introduction to Analog and Digital Electronics", "credits": 4 },
    "ES105": { "title": "Electrical and Electronics Lab", "credits": 2 },
    "ES106": { "title": "Manufacturing and Workshop practice", "credits": 4 },
    "PH101": { "title": "Physics", "credits": 4 },
    "CH202": { "title": "Chemistry Lab", "credits": 2 },
    "PE102": { "title": "Physical Education", "credits": 0 },
    "FP101": { "title": "Intro to Engineering", "credits": 1 },
    "HS221": { "title": "Introduction to Philosophy", "credits": 4 },
    "MA201": { "title": "Mathematics III", "credits": 4 },
    "ES201": { "title": "Intro to Design and Innovation", "credits": 4 },
    "CH201": { "title": "General Chemistry", "credits": 4 },
    "PH102": { "title": "Physics Lab", "credits": 2 },
    "PE103": { "title": "Physical Education", "credits": 0 },
    "MA202": { "title": "Mathematics IV", "credits": 4 },
    "ES202": { "title": "Introduction to Materials", "credits": 4 },
    "ES212": { "title": "Fluid Mechanics", "credits": 4 },
    "ES221": { "title": "Mechanics of Solids", "credits": 4 },
    "PE104": { "title": "Physical Education", "credits": 0 }
  }
}]
const branches = {
  "Artificial Intelligence": {
    branchCode: "AI", branchName: "Artificial Intelligence",
    totalCredits: 171, coreCredits: 44, electiveCredits: 20,
    mandatoryScienceBasketRequirements: "Specified by parent discipline out of the chemistry, cognitive science, earth sciences and physics options",
    mandatoryMathBasketRequirements: "2 credits worth of courses specified by parent discipline",
    openElectiveRequirements: { admitted_2023_2024: 16, admitted_2025_onwards: 20 },
    projectRequirements: "4 credits Open Project Course required after first year. Up to 16 credits of project courses can be counted towards graduation requirements.",
    disciplineCoreCourses: [
      { code: "DSA-I", title: "Data Structures & Algorithms I", credits: 4 },
      { code: "SSRP", title: "Signals, Systems & Random Processes", credits: 4 },
      { code: "DS", title: "Digital Systems", credits: 4 },
      { code: "TOC", title: "Theory of Computing", credits: 4 },
      { code: "MFAI", title: "Mathematical Foundations for AI", credits: 4 },
      { code: "CS", title: "Control Systems", credits: 4 },
      { code: "STTAI", title: "Software Tools & Techniques for AI", credits: 4 },
      { code: "COA", title: "Computer Organization & Architecture", credits: 4 },
      { code: "FAIMS", title: "Foundations of AI: Multiagent Systems", credits: 4 },
      { code: "ML", title: "Machine Learning", credits: 4 },
      { code: "IDS", title: "Introduction to Data Science", credits: 4 },
    ],
    disciplineElectiveBaskets: [
      {
        basketName: "CSE Basket", minimumCredits: 4,
        courses: [
          { code: "CS301", title: "Operating Systems", credits: 4 },
          { code: "CS327", title: "Compilers", credits: 4 },
          { code: "CS432", title: "Databases", credits: 4 },
          { code: "CS433", title: "Computer Networks", credits: 4 },
          { code: "ES214", title: "Discrete Mathematics", credits: 4 },
          { code: "TBD-SE", title: "Software Engineering", credits: 4 },
        ],
      },
      {
        basketName: "General AI Electives", minimumCredits: 16,
        courses: [
          { code: "CS333", title: "Ethics of AI", credits: 4 },
          { code: "CS613", title: "Natural Language Processing", credits: 4 },
          { code: "ES615", title: "Nature Inspired Computing", credits: 4 },
          { code: "ES661", title: "Probabilistic Machine Learning", credits: 4 },
          { code: "ES666", title: "Computer Vision", credits: 4 },
          { code: "ES667", title: "Deep Learning", credits: 4 },
          { code: "ME639", title: "Introduction to Robotics", credits: 4 },
          { code: "TBD-RL", title: "Reinforcement Learning", credits: 4 },
          { code: "TBD-GT", title: "Game Theory", credits: 4 },
        ],
      },
    ],
  },
  "Computer Science & Engineering": {
    branchCode: "CSE", branchName: "Computer Science & Engineering",
    totalCredits: 170, coreCredits: 36, electiveCredits: 26,
    mandatoryScienceBasketRequirements: "Any approved course from Science Basket",
    mandatoryMathBasketRequirements: "2 credits worth of courses from Mathematics Basket",
    openElectiveRequirements: { admitted_2022_to_2024: 16, admitted_2025_onwards: 20 },
    projectRequirements: "4 credits Open Project Course required. Online/CS projects can contribute at most 8 credits as discipline electives.",
    disciplineCoreCourses: [
      { code: "ES242", title: "Data Structures & Algorithms I", credits: 4 },
      { code: "ES214", title: "Discrete Mathematics", credits: 4 },
      { code: "ES203", title: "Digital Systems", credits: 4 },
      { code: "ES215", title: "Computer Organization and Architecture", credits: 4 },
      { code: "CS302", title: "Theory of Computation", credits: 4 },
      { code: "CS301", title: "Operating Systems", credits: 4 },
      { code: "CS434", title: "Software Tools and Techniques for CSE", credits: 4 },
      { code: "CS459", title: "Foundations of AI: Multiagent Systems", credits: 4 },
      { code: "CS460", title: "Computer Networks", credits: 4 },
    ],
    disciplineElectiveBaskets: [
      {
        basketName: "Theory & Algorithms Basket", minimumCredits: 8,
        courses: [
          { code: "ES301", title: "Data Structures & Algorithms II", credits: 4 },
          { code: "CS614", title: "Advanced Algorithms", credits: 4 },
          { code: "CS617", title: "Computational Complexity Theory", credits: 4 },
          { code: "CS328", title: "Introduction to Data Science", credits: 4 },
        ],
      },
      {
        basketName: "Systems Basket", minimumCredits: 8,
        courses: [
          { code: "CS327", title: "Compilers", credits: 5 },
          { code: "CS432", title: "Databases", credits: 5 },
          { code: "CS431", title: "Computer and Network Security", credits: 4 },
          { code: "CS435", title: "Human-Computer Interaction", credits: 4 },
          { code: "CS616", title: "Parallel and Distributed Systems", credits: 4 },
        ],
      },
    ],
  },
  "Electrical Engineering": {
    branchCode: "EE", branchName: "Electrical Engineering",
    totalCredits: 175, coreCredits: 43, electiveCredits: 20,
    mandatoryScienceBasketRequirements: "PH 201: Introduction to Electrodynamics is mandatory.",
    mandatoryMathBasketRequirements: "2 credits worth of courses from Mathematics Basket",
    openElectiveRequirements: { admitted_2022_to_2024: 16, admitted_2025_onwards: 24 },
    projectRequirements: "Project courses and online EE courses do not count towards discipline-specific electives.",
    disciplineCoreCourses: [
      { code: "SSRP", title: "Signals, Systems & Random Processes", credits: 4 },
      { code: "EE221", title: "Electronic Devices / Semiconductor Devices", credits: 4 },
      { code: "EE331", title: "Electrical Machines", credits: 4 },
      { code: "ES331", title: "Power Systems", credits: 4 },
      { code: "ES332", title: "Control Systems / Control Theory", credits: 4 },
      { code: "EE311", title: "Engineering Electromagnetics", credits: 4 },
      { code: "EE321", title: "Analog & Mixed Signal Circuits", credits: 5 },
      { code: "EE333", title: "Power Electronics", credits: 4 },
      { code: "EE411", title: "Digital Signal Processing", credits: 4 },
      { code: "EE341", title: "Communication Systems", credits: 4 },
    ],
    disciplineElectiveBaskets: [
      {
        basketName: "All EE Elective Courses", minimumCredits: 20,
        courses: [
          { code: "ES333", title: "Microprocessors and Embedded Systems", credits: 4 },
          { code: "ES613", title: "Modern Control Theory", credits: 4 },
          { code: "ES616", title: "Digital Control Systems", credits: 4 },
          { code: "ES663", title: "Smart Renewable Energy Systems", credits: 4 },
          { code: "ES667", title: "Deep Learning", credits: 4 },
          { code: "ES668", title: "5G and Beyond", credits: 4 },
          { code: "ES666", title: "Computer Vision", credits: 4 },
          { code: "PH643", title: "Quantum Computing and Information", credits: 4 },
        ],
      },
    ],
  },
  "Mechanical Engineering": {
    branchCode: "ME", branchName: "Mechanical Engineering",
    totalCredits: 169, coreCredits: 44, electiveCredits: 20,
    mandatoryScienceBasketRequirements: "One course among PH 201, PH 202, PH 404, CH 203, CH 204 is mandatory.",
    mandatoryMathBasketRequirements: "2 credits worth of courses from Mathematics Basket",
    openElectiveRequirements: { admitted_2022_to_2024: 16, admitted_2025_onwards: 24 },
    projectRequirements: "Online ME courses do not count towards discipline-specific electives. ME project courses can contribute at most 8 credits.",
    disciplineCoreCourses: [
      { code: "THERMO", title: "Thermodynamics", credits: 3 },
      { code: "SD", title: "Statics & Dynamics", credits: 4 },
      { code: "FD", title: "Fluid Dynamics", credits: 5 },
      { code: "MOS", title: "Mechanics of Solids", credits: 4 },
      { code: "PMP", title: "Principles of Manufacturing Processes", credits: 3 },
      { code: "HMT", title: "Heat and Mass Transfer", credits: 4 },
      { code: "CS", title: "Control Systems", credits: 4 },
      { code: "SAM", title: "Synthesis and Analysis of Mechanisms", credits: 3 },
      { code: "MSD", title: "Mechanical Systems Design", credits: 3 },
    ],
    disciplineElectiveBaskets: [
      {
        basketName: "All ME Elective Courses", minimumCredits: 20,
        courses: [
          { code: "ES408", title: "Mechatronics", credits: 4 },
          { code: "ES604", title: "Engineering Optimization", credits: 4 },
          { code: "ES621", title: "Advanced Solid Mechanics", credits: 4 },
          { code: "ES622", title: "Finite Element Methods", credits: 4 },
          { code: "ES631", title: "Advanced Heat Transfer", credits: 4 },
          { code: "ES656", title: "Human-Robot Interaction", credits: 4 },
          { code: "MSE313", title: "Polymers, Ceramics & Composites", credits: 4 },
        ],
      },
    ],
  },
  "Civil Engineering": {
    branchCode: "CE", branchName: "Civil Engineering",
    totalCredits: 172, coreCredits: 42, electiveCredits: 20,
    mandatoryScienceBasketRequirements: "Any approved course from Science Basket",
    mandatoryMathBasketRequirements: "2 credits worth of courses from Mathematics Basket",
    openElectiveRequirements: { admitted_2022_to_2024: 16, admitted_2025_onwards: 24 },
    projectRequirements: "4 credits Field Survey / Comprehensive Project required.",
    disciplineCoreCourses: [
      { code: "MOS", title: "Mechanics of Solids", credits: 4 },
      { code: "SA", title: "Structural Analysis", credits: 4 },
      { code: "FM", title: "Fluid Mechanics", credits: 4 },
      { code: "HH", title: "Hydrology & Hydraulics", credits: 4 },
      { code: "DSS", title: "Design of Steel Structures", credits: 4 },
      { code: "SM", title: "Soil Mechanics", credits: 5 },
      { code: "DRCS", title: "Design of Reinforced Concrete Structures", credits: 5 },
      { code: "CTM", title: "Construction Technology & Management", credits: 4 },
    ],
    disciplineElectiveBaskets: [
      {
        basketName: "Design/Applications Basket", minimumCredits: 12,
        courses: [
          { code: "CE313", title: "Environmental Science and Engineering", credits: 4 },
          { code: "CE314", title: "Geotechnical Engineering", credits: 4 },
          { code: "CE404", title: "Transportation Engineering", credits: 4 },
        ],
      },
      {
        basketName: "General CE Electives Basket", minimumCredits: 8,
        courses: [
          { code: "CE607", title: "Advanced Structural Analysis", credits: 4 },
          { code: "CE622", title: "Structural Dynamics", credits: 4 },
          { code: "CE626", title: "Earthquake Engineering", credits: 4 },
          { code: "CE632", title: "Advanced Concrete Design", credits: 4 },
          { code: "CE635", title: "Pavement Materials and Design", credits: 4 },
          { code: "CE636", title: "Traffic and Roadway Engineering", credits: 4 },
        ],
      },
    ],
  },
  "Chemical Engineering": {
    branchCode: "CH", branchName: "Chemical Engineering",
    totalCredits: 170, coreCredits: 42, electiveCredits: 20,
    mandatoryScienceBasketRequirements: "Any approved course from Science Basket",
    mandatoryMathBasketRequirements: "2 credits worth of courses from Mathematics Basket",
    openElectiveRequirements: { admitted_2022_to_2024: 16, admitted_2025_onwards: 24 },
    projectRequirements: "Open Project Course (4 credits) required after first year.",
    disciplineCoreCourses: [
      { code: "CPC", title: "Chemical Process Calculations", credits: 3 },
      { code: "CET", title: "Chemical Engineering Thermodynamics", credits: 3 },
      { code: "PFM", title: "Process Fluid Mechanics", credits: 3 },
      { code: "CRE1", title: "Chemical Reaction Engineering I", credits: 3 },
      { code: "HT", title: "Heat Transfer", credits: 3 },
      { code: "SP1", title: "Separation Processes I", credits: 3 },
      { code: "PDC", title: "Process Dynamics & Control", credits: 3 },
      { code: "PSDS", title: "Process Synthesis, Design & Simulation", credits: 4 },
    ],
    disciplineElectiveBaskets: [
      {
        basketName: "Chemical Engineering Elective Basket", minimumCredits: 20,
        courses: [
          { code: "CL324", title: "Introduction to Polymer Science and Engineering", credits: 4 },
          { code: "CL426", title: "Biochemical Engineering", credits: 4 },
          { code: "ES604", title: "Engineering Optimization", credits: 4 },
          { code: "CL601", title: "Advance Transport Phenomena", credits: 4 },
          { code: "CL602", title: "Advanced Thermodynamics", credits: 4 },
          { code: "CL604", title: "Advanced Reaction Engineering", credits: 4 },
          { code: "CE634", title: "Air Pollution Control Engineering", credits: 4 },
        ],
      },
    ],
  },
  "Materials Engineering": {
    branchCode: "MSE", branchName: "Materials Engineering",
    totalCredits: 175, coreCredits: 42, electiveCredits: 20,
    mandatoryScienceBasketRequirements: "One course among PH 201, PH 202, CH 203 is mandatory.",
    mandatoryMathBasketRequirements: "2 credits worth of courses from Mathematics Basket",
    openElectiveRequirements: { admitted_2022_to_2024: 16, admitted_2025_onwards: 24 },
    projectRequirements: "MSE 299/399/499 courses of up to 8 credits can be counted towards discipline-specific electives.",
    disciplineCoreCourses: [
      { code: "SOM", title: "Structure of Materials", credits: 4 },
      { code: "MT", title: "Materials Thermodynamics", credits: 4 },
      { code: "ME", title: "Microstructural Engineering", credits: 4 },
      { code: "POM", title: "Physics of Materials", credits: 4 },
      { code: "MBM", title: "Mechanical Behaviour of Materials", credits: 4 },
      { code: "PCC", title: "Polymers, Ceramics and Composites", credits: 4 },
      { code: "MP", title: "Materials Processing", credits: 4 },
      { code: "CDM", title: "Corrosion & Degradation of Materials", credits: 4 },
    ],
    disciplineElectiveBaskets: [
      {
        basketName: "MSE Elective Basket", minimumCredits: 20,
        courses: [
          { code: "MSE-ALL", title: "All courses with MSE prefix and ES 623/ES 415", credits: 4 },
        ],
      },
    ],
  },
  "Integrated Circuit Design & Technology": {
    branchCode: "IC", branchName: "Integrated Circuit Design & Technology",
    totalCredits: 173, coreCredits: 44, electiveCredits: 20,
    mandatoryScienceBasketRequirements: "One course among PH 203, PH 510, Physics of Materials is mandatory.",
    mandatoryMathBasketRequirements: "2 credits worth of courses specified by parent discipline",
    openElectiveRequirements: { admitted_2024: 16, admitted_2025_onwards: 24 },
    projectRequirements: "Open Project Course (4 credits) mandatory after first year.",
    disciplineCoreCourses: [
      { code: "USW", title: "Unveiling the Semiconductor World", credits: 2 },
      { code: "SSRP", title: "Signals, Systems & Random Processes", credits: 4 },
      { code: "DS", title: "Digital Systems", credits: 4 },
      { code: "AMSC", title: "Analog & Mixed Signal Circuits", credits: 4 },
      { code: "CMOS", title: "CMOS Circuit Design", credits: 4 },
      { code: "SD", title: "Semiconductor Devices", credits: 4 },
      { code: "ICFM", title: "IC Fabrication & Manufacturing", credits: 4 },
      { code: "SPAM", title: "Semiconductor Package Assembly & Manufacturing", credits: 4 },
      { code: "ICFL", title: "IC Fabrication Lab", credits: 2 },
    ],
    disciplineElectiveBaskets: [
      {
        basketName: "IC Design Electives", minimumCredits: 20,
        courses: [
          { code: "EE651", title: "CMOS Analog IC Design", credits: 4 },
          { code: "EE660", title: "Power Management IC Design", credits: 4 },
          { code: "ES672", title: "Semiconductor Packaging", credits: 4 },
          { code: "TBD-RF", title: "RF IC Design", credits: 4 },
          { code: "TBD-VLSI", title: "VLSI Physical Design: Netlist to GDSII", credits: 4 },
          { code: "TBD-MEMS", title: "Fundamentals of MEMS/NEMS", credits: 4 },
        ],
      },
    ],
  },
};

const instituteRequirements = {
  hssBasket: {
    totalCredits: 20,
    mandatoryCourses: [
      { code: "HS191", title: "Introduction to Writing I", credits: 2 },
      { code: "HS192", title: "Introduction to Writing II", credits: 2 },
      { code: "HS151", title: "Economics", credits: 4 },
    ],
    electiveCredits: 12,
    generalEducationCredits: 4,
  },
  scienceBasket: {
    basketCredits: 8,
    basicScienceElectiveCredits: 4,
    allowedAreas: [
      "Chemistry",
      "Cognitive Science",
      "Earth Sciences",
      "Physics",
    ],
  },
  mathBasket: {
    mandatoryCourses: [
      {
        code: "MA103",
        title: "Calculus of Single Variable & Linear Algebra",
        credits: 4,
      },
      { code: "MA104", title: "Ordinary Differential Equations", credits: 2 },
      { code: "MA203", title: "Numerical Methods", credits: 2 },
    ],
    basketCredits: 2,
  },
  materialsBasket: {
    totalCredits: 3,
    options: [
      { code: "ES118", title: "Materials for the Future", credits: 3 },
      {
        code: "MSE211",
        title: "Material Characterization Techniques",
        credits: 3,
      },
      { code: "MSE314", title: "Materials Selection and Design", credits: 3 },
    ],
  },
  openProject: { mandatoryCredits: 4, courseCode: "XX-XXX" },
  openElectives: { admitted_2022_to_2024: 16, admitted_2025_onwards: 20 },
  physicalEducation: { mandatorySemesters: 4, credits: 0 },
  graduationCredits: { range: "169-175" },
};

export default courseslist;
export{
    instituteRequirements,branches
}
